### PR TITLE
Update liveness status

### PR DESCRIPTION
**Pull request by micksi**
PR for issue in cloud-health-connect
https://github.com/CloudNativeJS/cloud-health-connect/issues/5

Took the chance of updating the tests as well as some of them reported wrong status since their async behaviour wasn't handled correct

### CODE REVIEW

**Comment by micksi** [comment]
@BethGriggs been looking into how readinessCheck should support the reevaluation but when I look at the getStatus method it should probably be redesigned and I think the whole flow is a little flawed if readiness and liveness should be implemented according to spec. The internal startupComplete state in HealthChecker seems unnecessary if readiness means "ready for traffic" and not "startup complete" as it was previously used for. 

I would expect all checks should have their own getStatus methods (getLivenessStatus, getReadinessStatus, getShutdownStatus). Then cloud-heatlth-connect endpoints (LivenessEndpoint, etc.) should check their respected status instead of just getStatus.

@seabaylea would you like to chime in on this as well?

**Comment by seabaylea** [comment]
@micksi sorry, I've only just seen that this is here. Yes, we absolutely should clean this up. I think there's four types of check need to support:
* Startup (single shot, startup only)
* Readiness (multi-execute, runtime only)
* Liveness (multi-execute, runtime only)
* Shutdown (single short, shutdown only)

I agree, we should also support separate "getStatus()" calls for each, as well as a combined option (which could be used for a single endpoint).

You're changes look like a really good starting point. Are you happy to sign the CLA and re-base, or are you ok for me to build off what you have?

**Comment by micksi** [comment]
@seabaylea should have signed the CLA now. About the Startup check I think it would be a nice addition but it is not part of the kubernetes spec and I think it should be left to not confuse people using the library. 
Please keep me updated if I can help in anyway.

**Comment by raymondfeng** [comment]
I'm running similar issues here as the promise handling is pretty messy. We should use `async/await` to clean up the code.

**Comment by andrewhughes101** [comment]
@micksi gonna go ahead and close this as I think the changes have been addressed. Feel free to let me know if they havent.

**Pull request closed without merging**
